name: SKIcalculus
version: 0.1.0.0
github: 'aronerben/SKIcalculus'
license: BSD3
author: 'Aron Erben'
maintainer: 'aronerben@gmail.com'
copyright: '2021 Aron Erben'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/aronerben/SKIcalculus#readme>

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - text
  - mtl
  - recursion-schemes
  - containers
  - free

library:
  source-dirs: src
  ghc-options:
    - -Wall
  #   - -Werror

executables:
  SKIcalculus-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - SKIcalculus
    when:
      - condition: false
        other-modules: Paths_SKIcalculus

tests:
  SKIcalculus-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - SKIcalculus
    when:
      - condition: false
        other-modules: Paths_SKIcalculus
